#!/usr/bin/env python3
"""
scan-project.py — Deterministic project scanner for shared-update-docs-project-standard skill.

Detects whether the project documentation file needs to be regenerated by comparing
the generatedAtCommit stored in _bmad-docs/project.md against the base branch tip.

Usage:
    python scripts/scan-project.py [--root /path/to/repo]
                                   [--base-branch origin/main]
                                   [--doc-file _bmad-docs/project.md]

Base branch:
    Auto-detected from the repo (git symbolic-ref refs/remotes/origin/HEAD).
    Override with --base-branch if needed (e.g. origin/develop, main, master).

Change detection:
    Compares generatedAtCommit..<base-branch> using --first-parent.
    Works correctly regardless of whether the repo uses squash-merge or regular merge.

Output:
    JSON report to stdout — used by 00-init.md to present scan results.
    Exit code 0 on success, 1 on fatal error.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def run_git(args: list, cwd: Path) -> str:
    """Run a git command and return stdout stripped. Returns '' on any error."""
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        return result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return ""


def detect_base_branch(root: Path) -> str:
    """Auto-detect the default remote branch. Resolution order:
    1. git symbolic-ref refs/remotes/origin/HEAD  → e.g. refs/remotes/origin/main
    2. git remote show origin (slower, requires network)
    3. Fallback: origin/main
    """
    # Fast local lookup — works if `git fetch` has been run at least once
    ref = run_git(["symbolic-ref", "refs/remotes/origin/HEAD"], root)
    if ref:
        # refs/remotes/origin/main → origin/main
        return ref.replace("refs/remotes/", "", 1)

    # Slower network call
    output = run_git(["remote", "show", "origin"], root)
    for line in output.splitlines():
        line = line.strip()
        if line.startswith("HEAD branch:"):
            branch = line.split(":", 1)[1].strip()
            if branch and branch != "(unknown)":
                return f"origin/{branch}"

    return "origin/main"


def get_head_commit(root: Path, base_branch: str) -> str:
    """Return the tip of base_branch as the commit SHA to store as generatedAtCommit.
    Using the tip of the base branch (rather than HEAD) ensures the stored SHA always
    exists on the main branch — safe for both squash-merge and regular merge workflows.
    Falls back to HEAD if base_branch is unavailable (e.g. offline / shallow clone).
    """
    sha = run_git(["rev-parse", base_branch], root)
    if sha:
        return sha
    return run_git(["log", "-1", "--format=%H"], root)


def get_commits_since(commit: str, root: Path, base_branch: str) -> list:
    """Return commit onelines since commit on base_branch (--first-parent).
    Counts only commits that landed on the main branch, ignoring feature-branch history.
    Works for both squash-merge and regular merge.
    """
    output = run_git(
        ["log", f"{commit}..{base_branch}", "--first-parent", "--oneline"],
        root,
    )
    if not output:
        return []
    return output.splitlines()


# ---------------------------------------------------------------------------
# Documentation status
# ---------------------------------------------------------------------------

_COMMIT_RE = re.compile(r'generatedAtCommit:\s*["\']?([a-f0-9]{7,40})["\']?')
_DATE_RE = re.compile(r'lastUpdated:\s*["\']?([\d]{4}-[\d]{2}-[\d]{2})["\']?')


def read_doc_frontmatter(doc_path: Path) -> dict:
    """Read generatedAtCommit and lastUpdated from YAML frontmatter (first 20 lines)."""
    result = {"generated_at_commit": None, "last_updated": None}
    if not doc_path.exists():
        return result
    try:
        with open(doc_path, encoding="utf-8") as fh:
            for i, line in enumerate(fh):
                if i >= 20:
                    break
                if result["generated_at_commit"] is None:
                    m = _COMMIT_RE.search(line)
                    if m:
                        result["generated_at_commit"] = m.group(1)
                if result["last_updated"] is None:
                    m = _DATE_RE.search(line)
                    if m:
                        result["last_updated"] = m.group(1)
    except OSError:
        pass
    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Scan project documentation status for shared-update-docs-project-standard skill."
    )
    parser.add_argument(
        "--root", default=".",
        help="Project root directory (default: current working directory)"
    )
    parser.add_argument(
        "--base-branch", default=None,
        help="Override the base branch reference (e.g. origin/develop, main). "
             "Auto-detected from the repo if not specified."
    )
    parser.add_argument(
        "--doc-file", default="_bmad-docs/project.md",
        help="Path to the project documentation file, relative to --root "
             "(default: _bmad-docs/project.md)"
    )
    args = parser.parse_args()

    repo_root = Path(args.root).resolve()
    doc_path = repo_root / args.doc_file
    base_branch = args.base_branch or detect_base_branch(repo_root)
    head_commit = get_head_commit(repo_root, base_branch)

    frontmatter = read_doc_frontmatter(doc_path)
    generated_at = frontmatter["generated_at_commit"]
    last_updated = frontmatter["last_updated"]

    # Compute days since last update
    days_since_last = None
    if last_updated:
        try:
            d = date.fromisoformat(last_updated)
            days_since_last = (date.today() - d).days
        except ValueError:
            pass

    # Determine status
    if not doc_path.exists():
        status = "missing"
        reason = "No documentation file found"
        commits_since_last = []
    elif not generated_at:
        status = "needs_update"
        reason = "No generatedAtCommit reference in frontmatter"
        commits_since_last = []
    else:
        commits_since_last = get_commits_since(generated_at, repo_root, base_branch)
        if commits_since_last:
            status = "needs_update"
            reason = f"{len(commits_since_last)} commit(s) since last documentation"
        else:
            status = "up_to_date"
            reason = "No changes since last documentation"

    report = {
        "scan_completed": True,
        "base_branch": base_branch,
        "current_head_commit": head_commit,
        "doc_file": str(doc_path.relative_to(repo_root)),
        "project_status": status,
        "reason": reason,
        "generated_at_commit": generated_at,
        "last_updated": last_updated,
        "days_since_last": days_since_last,
        "commits_since_last": commits_since_last,
        "commits_count": len(commits_since_last),
    }

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
